# User config
author: "Caio MGA"
tagline: "Caio MGA - Game Dev - Unity"
about: "Sou Caio MGA, Desenvolvedor de Games Unity/HTML5. Atuo na área de T.I. desde 2011, trabalho exclusivamente com jogos desde 2017. Aos 4 anos de idade ganhei um Master System III num pacote de Ruffles, virar gamedev era destino."
keywords: "Caio MGA, gamedev, c-sharp, C#, unity, javascript, phaser, pixi"
email: "caiomga@gmail.com"

social-media:
  - site: 
    name: LinkedIn
    url: "https://www.linkedin.com/in/caiomga/"
  - site:
    name: Github
    url: "https://github.com/CaioMGA"
  - site:
    name: Bitbucket
    url: "https://bitbucket.org/CaioMGA/"
  - site:
    name: itch.io
    url: "https://caiomga.itch.io/"
  - site:
    name: Unity Connect
    url: "https://connect.unity.com/u/caio-marchi-gomes-do-amaral"

skills-programming:
  - name: Unity Engine
    percent: 9
  - name: JavaScript
    percent: 7
  - name: C#
    percent: 7
  - name: Git (Github)
    percent: 6
  - name: Tools Programming
    percent: 6
  - name: Phaser/Pixi
    percent: 6
  - name: HLSL (Shaders)
    percent: 5
  - name: Automação
    percent: 4
  - name: node.js
    percent: 4
  
skills-other:
  - name: 2D
    percent: 9
  - name: 3D
    percent: 7
  - name: Trabalho Remoto
    percent: 9
  - name: Trabalho em Equipe
    percent: 9
  - name: Presentation
    percent: 9
  - name: Web
    percent: 8
  - name: Mobile (Android e iOS)
    percent: 7
  - name: VFX
    percent: 6
  - name: UI/UX
    percent: 6
  - name: Animation
    percent: 6

repo-url: https://github.com/CaioMGA/caiomga.github.io
jekyll-url: https://jekyllrb.com/
pineapple-url: https://arnolds.io/pineapple/ 

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed