# User config
author: "Caio Amaral"
tagline: "Caio Amaral - Game Dev - Unity"
about: "I’m Caio Amaral, 30 years old, brazilian, Game Developer. I worked on the I.T. field since 2011 and switched to game development on 2017. When I was 4 years old I won a videogame on a pack of chips. Becoming a Game Developer was destiny."
keywords: "Caio Amaral, gamedev, c-sharp, C#, unity, javascript, phaser, pixi, ui, tooling"
email: "caiomga@gmail.com"

social-media:
  - site: 
    name: LinkedIn
    url: "https://www.linkedin.com/in/caiomga/"
  - site:
    name: Github
    url: "https://github.com/CaioMGA"
  - site:
    name: Bitbucket
    url: "https://bitbucket.org/CaioMGA/"
  - site:
    name: itch.io
    url: "https://caiomga.itch.io/"
  - site:
    name: web-link
    url: "http://caiomga.com"
  - site:
    name: blog
    url: "http://blog.caiomga.com"
  - site:
    name: wiki
    url: "http://wiki.caiomga.com"

skills-programming:
  - name: Unity Engine
    percent: 9
  - name: C#
    percent: 9
  - name: Git (Github)
    percent: 8
  - name: JavaScript
    percent: 6
  - name: Tools Programming
    percent: 6
  - name: HLSL (Shaders)
    percent: 5
  - name: Automação
    percent: 4
  
skills-other:
  - name: 2D
    percent: 9
  - name: 3D
    percent: 6
  - name: Trabalho Remoto
    percent: 9
  - name: Trabalho em Equipe
    percent: 9
  - name: Presentation
    percent: 7
  - name: Mobile (Android e iOS)
    percent: 8
  - name: VFX
    percent: 7

repo-url: https://github.com/CaioMGA/caiomga.github.io
jekyll-url: https://jekyllrb.com/
pineapple-url: https://arnolds.io/pineapple/ 

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed